### PR TITLE
pycuda version control

### PR DESCRIPTION
**Pull request by astrobatty**
I changed the pycuda version check to not to force to use version 2017.1.1. This way the newest pycuda can be used as well.

### CODE REVIEW

**Comment by johnhoffmanxaxis** [comment]
Thanks for your contribution! I apologize for the delay.

**Comment by astrobatty** [comment]
The write access would be great! Thanks

**Comment by astrobatty** [comment]
@johnh2o2 could you please update the PyPI package along with a version update? Installing PyCUDA 2017.1.1. is a huge problem and pip install cuvarbase still requires it.

**Comment by johnh2o2** [comment]
Hi @astrobatty -- I'll take make an update of that a bit later today.

**Comment by johnh2o2** [comment]
Sorry, a little late, but did this earlier today, version should be updated to `0.2.1` now on pypi. Let me know if there are any issues!

**Pull request merged**
